version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: node
    steps:
      - add_ssh_keys
      - checkout
      - run:
          name: Setup git user
          command: |
            git config --global user.email "circleci@circleci.com"
            git config --global user.name "circleci"
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build and deploy
          command: npm run deploy
